<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item">
	<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
	<?php echo $this->getBeforePostContentHtml() ?>
	<?php echo $this->getAfterPostContentHtml() ?>
	<div class="post-entry entry<?php if ($post->getFeaturedImage): ?> post-entry-with-image<?php endif; ?>">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($featuredImage = $post->getFeaturedImage()): ?>
				<div class="featured-image left">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
				</div>
			<?php endif; ?>
			<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
				<?php echo $post->getPostExcerpt() ?>
			<?php else: ?>
				<?php
					$content = $post -> getPostContent ();
					$contentWordCount = count ( explode ( ' ', $content ) );
					if ( $contentWordCount > 100 )
					{	
						$contentShort = implode (' ', array_slice( explode( ' ', $content), 0, 25 ) );
						echo $contentShort . '&hellip;';
						echo '<p><button value="Read More" class="button" onclick="window.location=\'' . $post -> getPermalink () . '\'">Read More</button></p>';
					}
					else
					{
						echo $post -> getPostContent ();
					}
				?>
			<?php endif; ?>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
</div>