<?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>

	<nav role="navigation">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    <div class="nav navbar-nav">
		      	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header-primary-navigation')->toHtml(); ?>
			</div>
		</div>
	</nav>

<?php endif ?>